[workspace]
members = ["model", "connect/core", "connect/nonblocking"]

resolver = "2"

[workspace.package]
version = "5.0.0"                                            # NOTE remembe to update this and sbelow dependencies for byteserde and byteserde_derive
authors = ["Softstream <softstream.link@gmail.com>"]
readme = "readme.md"
license-file = "LICENSE"
edition = "2021"
rust-version = "1.69"
repository = "https://github.com/softstream-link/soupbintcp"
keywords = ["exchange", "protocol"]
categories = ["API bindings"]


[workspace.dependencies]
# used only by ouch_model
byteserde = { version = "0.4.0" }
byteserde_derive = { version = "0.4.0" }
byteserde_types = { version = "0.4.0" }
derive_more = { version = "0.99" }       # try_into, etc

chrono = { version = "0.4.26" }

soupbintcp_model = { version = "4.1", path = "../soupbintcp/model" }

# used only by ouch_connect_core
soupbintcp_connect_nonblocking = { version = "4.1", path = "../soupbintcp/connect/nonblocking" }
ouch_model = { path = "./model" }

# used only by ouch_connect_nonblocking
ouch_connect_core = { path = "./connect/core" }
# only used in unitests
links_core = { path = "../links/core" , features = ["unittest"]}

# logging
log = { version = "0.4" }
env_logger = { version = "0.10" }
colored = { version = "2.0" }
