[package]
name = "ouch_bindings_python"
version.workspace = true
authors.workspace = true
readme = "readme.md"
license-file.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ouch_connect_nonblocking"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = [
    "extension-module",
    "abi3",
    "abi3-py310",
] }
pyo3-log = "0.9" # allows rust logging to write to python logging
# py03 ={ workspace = true }
ouch_connect_nonblocking = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }

log = { workspace = true }
lazy_static = { workspace = true }

[dev-dependencies]
links_core = { workspace = true, features = ["unittest"] }


[build-dependencies]
pyo3-build-config = { version = "0.20" }
