# this is a cog generated python IDE interface file

# [[[cog
# import cog
# names = ["CltManual", "SvcManual", "CltAuto", "SvcAuto"]
# cog.out(
# f"""
# from types import TracebackType
# from links_connect.callbacks import Callback
# from typing import Iterable
# """
# )
# for name in names:
#   cog.out(
# f"""
# class {name}:
#     def __init__(self, host: str, callback: Callback, **kwargs) -> None: ...
#     def __enter__(self) -> {name}: ...
#     def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...
#     def send(self, msg: dict, io_timeout: float | None = None): ...
#     def is_connected(self, io_timeout: float | None = None) -> bool: ...
#     @property
#     @classmethod
#     def msg_samples(cls) -> Iterable[str]: ...
#
# """)
# ]]]

from types import TracebackType
from links_connect.callbacks import Callback
from typing import Iterable

class CltManual:
    def __init__(self, host: str, callback: Callback, **kwargs) -> None: ...
    def __enter__(self) -> CltManual: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...
    def send(self, msg: dict, io_timeout: float | None = None): ...
    def is_connected(self, io_timeout: float | None = None) -> bool: ...
    @property
    @classmethod
    def msg_samples(cls) -> Iterable[str]: ...


class SvcManual:
    def __init__(self, host: str, callback: Callback, **kwargs) -> None: ...
    def __enter__(self) -> SvcManual: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...
    def send(self, msg: dict, io_timeout: float | None = None): ...
    def is_connected(self, io_timeout: float | None = None) -> bool: ...
    @property
    @classmethod
    def msg_samples(cls) -> Iterable[str]: ...


class CltAuto:
    def __init__(self, host: str, callback: Callback, **kwargs) -> None: ...
    def __enter__(self) -> CltAuto: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...
    def send(self, msg: dict, io_timeout: float | None = None): ...
    def is_connected(self, io_timeout: float | None = None) -> bool: ...
    @property
    @classmethod
    def msg_samples(cls) -> Iterable[str]: ...


class SvcAuto:
    def __init__(self, host: str, callback: Callback, **kwargs) -> None: ...
    def __enter__(self) -> SvcAuto: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...
    def send(self, msg: dict, io_timeout: float | None = None): ...
    def is_connected(self, io_timeout: float | None = None) -> bool: ...
    @property
    @classmethod
    def msg_samples(cls) -> Iterable[str]: ...

# [[[end]]]
