# this is a cog generated python IDE interface file

# [[[cog
# import cog
# names = ["CltManual", "SvcManual", "CltAuto", "SvcAuto"]
# cog.out(
# f"""
# from types import TracebackType
# from ouch_connect import Callback, MsgDict
# """
# )
# for name in names:
#   cog.out(
# f"""
# class {name}:
#     def __enter__(self) -> {name}: ...
#     def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...
#     def send(self, msg: dict, io_timeout: float | None = None): ...
#     def is_connected(self, io_timeout: float | None = None) -> bool: ...
#     @property
#     def msg_samples(self) -> list[str]: ...
#
# """)
#   if name == "CltManual":
#    cog.out(
# f"""
#     def __init__(self, host: str, callback: Callback, connect_timeout: float | None = None, io_timeout: float | None = None, name: str | None = None) -> None: ...
# """)
#
#   if name == "SvcManual":
#    cog.out(
# f"""
#     def __init__(self, host: str, callback: Callback, max_connections: int | None = None, io_timeout: float | None = None, name: str | None = None) -> None: ...
# """)
#
#   if name == "CltAuto":
#    cog.out(
# f"""
#     def __init__(self, host: str, callback: Callback, usr: str, pwd: str, session: str, sequence: int, clt_max_hbeat_interval: float, svc_max_hbeat_interval: float, connect_timeout: float | None = None, io_timeout: float | None = None, name: str | None = None ) -> None: ...
# """)
#
#   if name == "SvcAuto":
#    cog.out(
# f"""
#     def __init__(self, host: str, callback: Callback, usr: str, pwd: str, session: str, clt_max_hbeat_interval: float, svc_max_hbeat_interval: float, max_connections: int | None = None, io_timeout: float | None = None, name: str | None = None) -> None: ...
# """)
# ]]]

from types import TracebackType
from ouch_connect import Callback, MsgDict

class CltManual:
    def __enter__(self) -> CltManual: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...
    def send(self, msg: dict, io_timeout: float | None = None): ...
    def is_connected(self, io_timeout: float | None = None) -> bool: ...
    @property
    def msg_samples(self) -> list[str]: ...


    def __init__(self, host: str, callback: Callback, connect_timeout: float | None = None, io_timeout: float | None = None, name: str | None = None) -> None: ...

class SvcManual:
    def __enter__(self) -> SvcManual: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...
    def send(self, msg: dict, io_timeout: float | None = None): ...
    def is_connected(self, io_timeout: float | None = None) -> bool: ...
    @property
    def msg_samples(self) -> list[str]: ...


    def __init__(self, host: str, callback: Callback, max_connections: int | None = None, io_timeout: float | None = None, name: str | None = None) -> None: ...

class CltAuto:
    def __enter__(self) -> CltAuto: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...
    def send(self, msg: dict, io_timeout: float | None = None): ...
    def is_connected(self, io_timeout: float | None = None) -> bool: ...
    @property
    def msg_samples(self) -> list[str]: ...


    def __init__(self, host: str, callback: Callback, usr: str, pwd: str, session: str, sequence: int, clt_max_hbeat_interval: float, svc_max_hbeat_interval: float, connect_timeout: float | None = None, io_timeout: float | None = None, name: str | None = None ) -> None: ...

class SvcAuto:
    def __enter__(self) -> SvcAuto: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...
    def send(self, msg: dict, io_timeout: float | None = None): ...
    def is_connected(self, io_timeout: float | None = None) -> bool: ...
    @property
    def msg_samples(self) -> list[str]: ...


    def __init__(self, host: str, callback: Callback, usr: str, pwd: str, session: str, clt_max_hbeat_interval: float, svc_max_hbeat_interval: float, max_connections: int | None = None, io_timeout: float | None = None, name: str | None = None) -> None: ...
# [[[end]]]
