name: Feature Branch Build
on:
  push:
      branches:
        - '*'
        - '!release*'

jobs:
  test-matrix:
    uses: softstream-link/workflows/.github/workflows/maturin-pytest-matrix-toolchain-os.yml@main
    with:
      fail-fast: false
      working-directory: "./bindings/python"
  clippy:
    uses: softstream-link/workflows/.github/workflows/maturin-clippy-toolchain.yml@main
  bench-matrix:
    uses: softstream-link/workflows/.github/workflows/maturin-bench-matrix-toolchain-os.yml@main
    with:
      fail-fast: false
