name: Branch `feature*` or Tag `*rc`
on:
  push:
      branches:
        - 'feature*'
      tags:
        - '*rc'
jobs:
  test-matrix:
    uses: softstream-link/workflows/.github/workflows/maturin-pytest-matrix-toolchain-os.yml@main
    with:
      fail-fast: false
      working-directory: "./bindings/python"
  clippy:
    uses: softstream-link/workflows/.github/workflows/maturin-clippy-toolchain.yml@main
  bench-matrix:
    uses: softstream-link/workflows/.github/workflows/maturin-bench-matrix-toolchain-os.yml@main
    with:
      fail-fast: false
  
  # fetch-test-secrets:
  #   runs-on: ubuntu-latest
  #   environment: test
  #   outputs:
  #     PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
  #   steps:
  #     - run: echo "environment=test, PYPI_API_TOKEN='${{ secrets.PYPI_API_TOKEN }}'"

  maturin-publish-test-pypi:
    # needs: fetch-test-secrets
    uses: softstream-link/workflows/.github/workflows/maturin-pypi-publish.yml@main
    with:
      os: '["ubuntu-latest"]'
      working-directory: "./bindings/python"
      environment: 'test'
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
