name: Feature Branch Build
on:
  push:
      branches:
        - '*'
        - '!release*'

jobs:
  test-matrix:
    uses: softstream-link/workflows/.github/workflows/rust-test-matrix-toolchain-os.yml@main
    with:
      fail-fast: false
      micromamba-env-file: ./bindings/python/micromamba/build_env.yaml
  clippy:
    uses: softstream-link/workflows/.github/workflows/rust-clippy-toolchain.yml@v1
  bench-matrix:
    uses: softstream-link/workflows/.github/workflows/rust-bench-matrix-toolchain-os.yml@v1
    with:
      fail-fast: false
