name: Branch `feature*` or Tag `*rc`
on:
  push:
      branches:
        - 'feature*'
      tags:
        - '*rc'
jobs:
  test-matrix:
    uses: softstream-link/workflows/.github/workflows/maturin-pytest-matrix-toolchain-os.yml@main
    with:
      fail-fast: false
      working-directory: "./bindings/python"
  clippy:
    uses: softstream-link/workflows/.github/workflows/maturin-clippy-toolchain.yml@main
  bench-matrix:
    uses: softstream-link/workflows/.github/workflows/maturin-bench-matrix-toolchain-os.yml@main
    with:
      fail-fast: false
  
  maturin-publish-test-pypi:
    uses: softstream-link/workflows/.github/workflows/maturin-pypi-publish.yml@main
    with:
      working-directory: "./bindings/python"
      environment: 'test' # needs both environment and secrets to work https://github.com/actions/runner/issues/1490
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }} # needs both environment and secrets to work https://github.com/actions/runner/issues/1490
